language: node_js
node_js: 6

cache:
  directories:
    - node_modules

os:
  - osx
  - linux

before_script:
  - npm prune

script:
  - npm run dist

notifications:
  slack: ramme:44ubE4BVf3FGi8OldEKL743J
  email: false
