environment:
  nodejs_version: '8'

platform:
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install npm -g

test_script:
  - npm run test

build_script:
  - npm run dist
